# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Contact"
url = "/#contact"
weight = 2

# footer menu
[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"

[[footer]]
name = "Terms & Conditions"
url = "/terms-conditions"